# Generated by Django 2.0.3 on 2018-10-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('location_x', models.FloatField(blank=True, default=0)),
                ('location_y', models.FloatField(blank=True, default=0)),
                ('capacity', models.IntegerField(blank=True, default=0)),
                ('resources', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
