# Generated by Django 2.0.3 on 2018-10-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='used_capacity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
