# Generated by Django 2.0.3 on 2018-10-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0003_shelter_used_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='location_x',
            new_name='location_lat',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='location_y',
            new_name='location_log',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='resources',
            new_name='resources_left',
        ),
    ]
