# Generated by Django 2.0.3 on 2018-10-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0006_auto_20181018_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missing_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
                ('aadhar', models.IntegerField(blank=True, default=1239819827839)),
                ('age', models.IntegerField(blank=True, default=34)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], null=True, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='NGOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(blank=True, default='', max_length=25)),
                ('organisation_type', models.CharField(blank=True, default='', max_length=35)),
                ('organisation_address', models.TextField()),
                ('area_of_volunteering', models.CharField(choices=[('', '-------'), ('dcr', 'Doctor'), ('elw', 'Electrical Works'), ('vls', 'Vehicle Support'), ('rlo', 'Relief operation'), ('cln', 'Cleaning'), ('bot', 'Boat Service'), ('oth', 'Other')], default=' ', max_length=50)),
                ('organisation_phone_no', models.IntegerField(blank=True, default=9993993287)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestee_name', models.CharField(blank=True, default='', max_length=15)),
                ('requestee_phone_no', models.IntegerField(blank=True, default=9993993287)),
                ('requestee_location', models.CharField(blank=True, default='', max_length=5)),
                ('location_lat', models.FloatField(blank=True, default=0)),
                ('location_log', models.FloatField(blank=True, default=0)),
                ('need', models.CharField(choices=[('', '-------'), ('resuce', 'Need Rescue'), ('resource', 'Nedd Resources'), ('both', 'Need Resue and Resources')], default=' ', max_length=50)),
            ],
        ),
    ]
