# Generated by Django 2.0.3 on 2018-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0007_missing_person_ngos_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Group', max_length=51, verbose_name='Name')),
                ('activeUser', models.IntegerField(blank=True, default=1)),
                ('strength', models.IntegerField(blank=True, default=1)),
                ('location', models.CharField(default='Location', max_length=100, verbose_name='Name')),
                ('location_lat', models.FloatField(blank=True, default=0)),
                ('location_log', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='missing_person',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=12, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=12, null=True, verbose_name='Gender'),
        ),
    ]
