# Generated by Django 2.0.3 on 2018-10-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0008_auto_20181019_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='peoples.Group'),
        ),
    ]
