# Generated by Django 2.0.3 on 2018-10-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0009_person_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='location',
        ),
        migrations.RemoveField(
            model_name='group',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='group',
            name='location_log',
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(default='Location', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='location_lat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='location_log',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
