# Generated by Django 2.1.2 on 2018-10-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0010_auto_20181020_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(default='Location', max_length=100, verbose_name='Location'),
        ),
    ]
