# Generated by Django 2.1.2 on 2018-10-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0011_auto_20181020_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='PersonID',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
