# Generated by Django 2.0.3 on 2018-10-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0013_auto_20181024_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='address',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
